#!/bin/bash
# Show the results from the test that was run

f=${1/\.tst/}
[ ! -x $f.tst ]  && cd $p/test 
[ -f $f.correct     ] && cat $f.correct && exit 0
[ -f $pt/$f.correct ] && cat $f.correct && exit 0
echo "No file found: $f.correct"
