#!/bin/bash
# Get the data from the server

curl localhost:$port/$1
echo

curl localhost:$port/list
echo

curl localhost:$port/post
echo
 
#curl -X POST http://localhost:$port/post -d '{"code": "print 456"}' -H "Content-Type: application/json"
curl localhost:$port/contact
echo
