#!/bin/bash
# Run the server

# Kill the old process
killall node

# Command line test
#node test-app.js

# Start the server
rbg node app.js
sleep 1

# Show the web page
rbg firefox localhost:8080/


