#!/bin/bash
# Show the pipe scan home page
echo 'Show the pipe scan home page in a browser'

cd ~/Documents/Code/hammer/commander/

# Kill the old process
killall node

# Start the server
rbg node app.js
sleep 1

# Show the web page
w localhost:8080

