#!/bin/bash
# Run the code to demo this project

./manage.py shell  <<EOF
from contact.models import test_code
test_code()
EOF

# Kill the old server
run-kill

# Run the server
rbg ./manage.py runserver $port
sleep 2

# Display the page
get_data
