#!/bin/bash
# Run the code to demo this project

# Kill the old server
x=`ps -ef | grep -v grep | grep runserver | awk '{ print $2 }'`
[ ! -z "$x" ] && echo kill $x && kill $x

# Run the server and display the page
manage.py runserver
sleep 2
firefox localhost:8000
