#!/usr/bin/env python
# Create the source code for a Django data type

from os.path import join,exists
from os import chdir,environ,listdir,mkdir
from sys import argv


# Find the names of all templates
def template_files():
    templates = [ 'dt.py',   'dt_views.py',  'dt_tests.py',    'dt_urls.py',
                  'dt.html', 'dt_list.html', 'dt_detail.html', 'dt_edit.html']
    return [ f for f in  listdir('snippets') if f in templates ]


# Convert source file
def convert_source(text, data_type, data_type_cap):
    text = text.replace('data_type',data_type)
    text = text.replace('Data_Type',data_type_cap)
    return text


# Print the source code
def show_code(path, text):
    show = False
    if show:
        print '----------------------------------------'
        print '    ',path
        print '----------------------------------------'
        print text
    else:
        print '    ',path


# Create source file
def create_source_file(f, data_type, data_type_cap):
    path = join('snippets',f)
    if not exists('code'):
        mkdir('code')
    code = join('code',f.replace('dt',data_type))
    if exists(path):
        text = open(path).read()
        f=open(code, 'w')
        text = convert_source(text, data_type, data_type_cap)
        f.write(text)
        f.close()
        show_code(code, text)
    else:
        print 'No snippet found, ', path


# Build all of the source code files
def build_source_files(data_type,data_type_cap):
    files =  template_files() 
    for f in files:
        create_source_file(f, data_type,data_type_cap)


# You must supply a class name
if len(argv)<2:
    print 'example usage: '+argv[0]+' EventMenu'
else:
    print "Create the source code for a Django data type, ", argv[1]
    build_source_files(argv[1].lower(),argv[1])
